### ISSUE TITLE
NCBI taxonomy DB out of date

### ISSUE THREAD

**Issue by nwheeler443** [taxoniq/taxoniq#20]
Hi, 

I'm finding a lot of taxon IDs from NCBI's taxonomy database are missing from taxoniq. This looks to be because they were added in 2022 and the latest taxoniq copy of the DB is from late 2021. Is there a way to generate more up to date versions of the database?

Best wishes, 

Nicole

**Comment by serenalotreck** [comment]
I'd like to second this! I'm using the `scientific_name` parameter, and even for strings that appear identically in the database when I use the online GUI search, produce key errors when using taxoniq.

For example, 'Pseudomonas fluorescens Pf-5' comes up with an [identical match online](https://www.ncbi.nlm.nih.gov/taxonomy/?term=Pseudomonas+fluorescens+Pf-5) but generates a `KeyError` with the following code:

```
import taxoniq

t1 = taxoniq.TAxon(scientific_name='Pseudomonas fluorescens Pf-5')
```

The error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/taxoniq/__init__.py", line 209, in __init__
    self.tax_id = self._get_db("sn2t")[scientific_name][0][0]
  File "marisa-trie/src/marisa_trie.pyx", line 577, in marisa_trie.BytesTrie.__getitem__
KeyError: 'Pseudomonas fluorescens Pf-5'
```

**Comment by kislyuk** [comment]
Hi all, thanks for your patience and apologies for the stale data. I ran into issues the last few times I tried to rebuild and publish the database built into Taxoniq (by reindexing Genbank). I will try again shortly and update here as soon as my other obligations allow.

**Comment by vpeddu** [comment]
Hi! Just wanted to bump to keep the issue from going stale. I am also running into issues where a bunch of newer taxIDs are missing

**Comment by PedroRaposo** [comment]
Hello.
I would also like to raise my concerns on this issue. Updating this data would be very useful.

**Comment by kislyuk** [comment]
Hi all, unfortunately I can't rebuild the taxoniq indexes and the taxonomy DB, because NCBI has corrupted the files for the genbank databases. Starting at some point in early 2022 and ongoing, NCBI's own documented tool for extracting data from genbank files, `blastdbcmd -db DB_NAME -entry all`, now consistently produces errors of the form "Error: [blastdbcmd] error while reading seqid".

I got in touch with NCBI about this issue, but my message was ignored.

Even though maintaining this package comes at a considerable cost and I receive no funding for it, I have been regularly looking into performing the updates - but this error completely blocks me, as this is the only method I know of to extract all records from a BLAST database.

**Comment by kislyuk** [comment]
OK, it looks like I've found a way to work around the error - hoping to make an updated release today or next weekend.

**Comment by kislyuk** [comment]
OK, thanks everyone for your patience, I've updated the indexes to the data available as of 2023-11-04, and everything appears to be working correctly after this 2-year hiatus. I'm making improvements to the indexing and release automation to make updating the indexes easier and more affordable in the future (this update cost hundreds of dollars in compute and storage).

> 'Pseudomonas fluorescens Pf-5' comes up with an [identical match online](https://www.ncbi.nlm.nih.gov/taxonomy/?term=Pseudomonas+fluorescens+Pf-5)

That is not an identical match, and updating the index won't solve that problem. This works though:
```
>>> taxoniq.Taxon(scientific_name='Pseudomonas protegens Pf-5')
taxoniq.Taxon(220664)
```
