### ISSUE TITLE
pip install failed building wheel for taxoniq

### ISSUE THREAD

**Issue by brmagalis** [taxoniq/taxoniq#21]
Hello! I am attempting to install taxoniq within a conda environment using the standard pip install, and I'm running into the following error:

      marisa-trie/src/agent.cpp:198:12: fatal error: longintrepr.h: No such file or directory
        198 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/home/brittany.rife/.conda/envs/nti_cm/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for taxoniq
  Running setup.py clean for taxoniq
Failed to build taxoniq
ERROR: Could not build wheels for taxoniq, which is required to install pyproject.toml-based projects

I am using python 3.11.5, pip 23.2.1, and conda 23.7.3.

Any ideas as to how to get around this?

**Comment by jenniferlu717** [comment]
I have the same problems. I can never install taxoniq in a conda environment and I have no idea why. It always ends with the failure to build wheels error.

**Comment by kislyuk** [comment]
This is due to a Cython version compatibility issue in your environment. However, I have released a general workaround for this issue. marisa-trie, a key dependency of this library that underpins its performance, has released a new version that compiles pre-built wheels. This frees taxoniq of the need to vendor marisa-trie, and now we depend on its PyPI distribution, which can use the pre-built wheels. This improvement was released in taxoniq v1.0.0.
